backend/routes/networks.js, backend/routes/shops.js
The super-user startup wizard was saving not saving the values entered on the web for the server  deployDir and the initial shop web3PK. This fixes that.
=> Super-user startup wizard not saving web3PK and deployDir

backend/config.js, backend/test/const.js, backend/test/dns.utils.test.js, backend/test/http.utils.test.js, backend/utils/deployShop.js, backend/utils/dns/index.js, backend/utils/http.js
This will make a request to the issuer to try and trigger AutoSSL before the user does.  It's a bit of a race between this and the user with the way things are right now.  It takes a couple of minutes for Let's Encrypt to resolve the new DNS record.
This also changes the DNS configuration to use the network-level configured IPFS gateway instead of hardcoded values.  We need to make sure that's pointed at the issuer(it is on primary deployments, prod and staging).
There's a reasonable chance this will do the thing before the user, but think we might still want to add some UI stall tactics(like a spinner!).
Ref: #118
=> AutoSSL priming

shop/src/utils/listing.js
This falls back to the `admin.network` config in state for `ipfsApi` as not everything sends  a sane config.  Specifically the super-admin CreateListing.
Fixes #146
=> config.ipfsApi not always available

backend/routes/shops.js
Adds some defensive checks and makes sure that a file was uploaded before trying to move it.  Don't think this is super common, but spotted this on the rinkeby backend recently.
Closes #148
=> Adds some defensive checks for files when using mv

backend/queues/queues.js
Adds "hash tag" prefixes for redis cluster support to Bull queues
- https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster
- https://redis.io/topics/cluster-spec#keys-hash-tags
=> Bull queue cluster support

backend/routes/printful.js, backend/routes/shops.js, backend/utils/emailer.js, backend/utils/printful.js, backend/utils/templates/email.js, backend/utils/templates/head.js
Closes #40.
Printful webhook doesn't have any signature or any kind of authorization in the requests. So, the webhook endpoint is kind of open now. Anyone can abuse it. Have added a `PRINTFUL_WEBHOOK_SECRET` environment variable to the backend, that can be used to make the endpoint not-so-static.
=> Forward shipping data from Printful

backend/routes/discounts.js
Ensure shopId overrides user fields, rather than the other way around.
=> Prevent setting discounts on other stores.

backend/routes/printful.js, backend/utils/printful.js
The route for getting the details of an order would fail if the order id is not found on the Prinful side.
The fix is to check the HTTP request status code before trying to interpret the JSON.
Should fix bug #191
=> Fix bug in Printful API route

backend/db/migrations/20200710134411-changeEventTypeToEnum.js, shop/src/pages/admin/settings/_VerifyButton.js, shop/src/pages/admin/settings/payments/List.js
Executing the queryInterface.changeColumn for 2 columns at once was causing some errors (because it involves backing up the data in an intermediary table).
See logs:
```
== 20200710134411-changeEventTypeToEnum: migrating =======
Executing (default): PRAGMA TABLE_INFO(`external_events`);
Executing (default): PRAGMA TABLE_INFO(`external_events`);
Executing (default): PRAGMA INDEX_LIST(`external_events`)
Executing (default): PRAGMA INDEX_LIST(`external_events`)
Executing (default): PRAGMA foreign_key_list(external_events)
Executing (default): PRAGMA foreign_key_list(external_events)
Executing (default): CREATE TABLE IF NOT EXISTS `external_events_backup` (`id` INTEGER PRIMARY KEY, `shop_id` INTEGER REFERENCES `shops` (`id`), `service` VARCHAR(255), `event_type` TEXT, `data` JSON, …
```
=> Fix migration

backend/routes/discounts.js
Prevent any possibility that a shop admin  can change their own discount to belong to another shop.
=> Harden the discount update route

backend/app.js, backend/package.json, backend/queues/ui.js, backend/routes/affiliate.js, backend/routes/auth.js, backend/routes/collections.js, backend/routes/discounts.js, backend/routes/domains.js, backend/routes/health.js, backend/routes/networks.js, backend/routes/orders.js, backend/routes/printful.js, backend/routes/products.js, backend/routes/shipping-zones.js, backend/routes/shops.js, backend/routes/stripe.js, backend/routes/tx.js, backend/routes/uphold.js, backend/routes/users.js, backend/sentry.js, backend/utils/handleLog.js, yarn.lock
Integrate with Sentry to capture:
- API server errors
- Listener errors
Refactored the API server to use https://github.com/express-promise-router.
This now sends uncaught exceptions thrown within any route to the custom error handler and also properly sends a 500 error back. Before this change, the exceptions were not caught (Express 4 does not do it automatically) and that would cause the server to not return any response (e.g. the front-end would hang waiting for a response ).
=> Sentry back-end integration

backend/utils/emailVerification.js, backend/utils/sellers.js
To fix an issue where if an admin has not deployed their shop yet the email verification flow would fail.
=> [Email verification] Redirect to back-end vs front-end URL

shop/src/pages/admin/settings/appearance/_CustomDomain.js
The custom domain DNS record instructions were incorrect for the DNSLink records.
Should be like the following:
example.domain.com  CNAME fs-autossl.ogn.app
_dnslink.example.domain.com  TXT "dnslink=/ipns/example.ogn.app"
These were tested and confirmed.
=> Fixes dnslink TXT record

backend/package.json, backend/utils/deployShop.js, yarn.lock
Use our own logger instead of ipfs-deploy's CLI "spinner"(orca).  This will prevent most of the ipfs-deploy logging from going to stderr confusing our monitoring.
Ref: https://github.com/ipfs-shipyard/ipfs-deploy/pull/174/files
=> Use our own logger with ipfs-deploy

backend/routes/domains.js
Fixes a few issues with the `/domains/verify-dns` endpoint.  Primarily `/api/v0/dns` returns IPFS hashes, not IPNS names, and IPFS hashes are case-sensitive.  Addressed a few other issues while there.
Fixes #282
=> DNS Verification Fixen

backend/routes/domains.js, backend/utils/dns/index.js, shop/src/pages/admin/settings/appearance/_CustomDomain.js, shop/src/utils/dns.js
DNS record suggestions were invalid for root-zone records(e.g. originprotocol.com).  This tries to mitigate that by suggesting the user create an A record for their shop when necessary.  If that IP changes we're in for a ton of hassle but I don't see us dropping that if we have a choice in the near future.  And this is better than preventing users from using root-zone records entirely.
This PR touches both the FE and BE.
Fixes #289
=> DNS Record Suggestions

backend/db/migrations/20200727184749-addStatusToShopDeployments.js, backend/enums.js, backend/models/shop_deployment.js, backend/routes/shops.js, backend/test/const.js, backend/test/shop.test.js, backend/test/utils.js, backend/utils/deployShop.js
Fix for #300 
- Added a new column status to shop_deployment and populate it in the deploy logic. It can have 3 values: Pending, Success, Failure
- Updated the logic so that before starting a new deployment, it checks there is no Pending deployment
- Added unit tests
=> Prevent concurrent deployments

backend/routes/shops.js, backend/test/shop.test.js, backend/utils/shop.js
Only allow [a-zA-Z0-9 ]
Other characters cause havoc with our URLs since we don't encode the shop name.
=> Restrict characters that can be used in the shop name

backend/routes/shops.js, backend/utils/printful.js
We should point printful webhooks to the backend URL (e.g. https://dshop/originprotocol.com) rather than at the shop's public URL which is only for FE routes (ex: https://store.brave.com).
Also added some extra logging to make it easy to grep using a shop id.
=> Use backend URL to register printful webhooks

backend/db/migrations/20200731205137-addPaymentCodeToOrder.js, backend/models/order.js, backend/test/order.test.js, backend/utils/handleLog.js
When troubleshooting payment/order related issues for orders placed with a credit card, it is nice to be able to link the following tables using the payment_code:
- external_payments
- transactions
- orders
This PR adds a new column payment_code to the orders table and populates it using the offer's data (we already store paymentCode in the offer's JSON data stored on IPFS).
=> Store payment_code in the orders tables

backend/package.json, backend/test/ipfs.utils.test.js, backend/utils/_ipfs.js, packages/ipfs/package.json, packages/ipfs/src/index.js, packages/utils/memoize.js, packages/utils/package.json
The back-end processing queue had a few failures caused by IPFS timeouts. All the retries failed with logs that look like this:
```
2020-08-02T04:49:47.198016519Z [INFO]  dshop.utils.handleLog: Event OfferCreated for listing Id 1-001-233
2020-08-02T04:49:47.201167573Z [DEBUG] dshop.utils.events: Upsert event...
2020-08-02T04:49:47.207408834Z [DEBUG] dshop.utils.events: Event exists
2020-08-02T04:49:47.210113302Z [INFO]  dshop.utils.handleLog: OfferCreated - 592 by 0xDF73aF150b8E446a6D39FDdc2CFA7Bf067B88936
2020-08-02T04:49:47.210283391Z [INFO]  dshop.utils.handleLog: IPFS Hash: QmYNkDPPDtX1QbDBrjLSBJwr66GabdDh6DHG6vXwmeYNoG
2020-08-02T04:49:47.215113744Z [INFO]  dshop.utils.handleLog: Using IPFS gateway https://ipfs.ogn.app for fetching offer data
2020-08-02T04:49:47.21534627Z [INFO] …
```
=> [IPFS get] Do not cache exceptions

backend/test/config.test.js, backend/utils/encryptedConfig.js
Fixes #358
Includes some tests.  This will chunk up some shops with utf-8 characters. There's 5 with no deployments and 2 are known broken.  The others can probably just be renamed and they'll be fine.
=> Use utf8 encoding for original charset for encrypted config

backend/scripts/validatePayments.js, backend/utils/stripe.js
A recent changes added metadata to the webhooks but legacy webhooks were not updated.
This script goes thru all the shops and verifies if their webhook is properly configured.
If not, it deletes the invalid webhook and creates a new one.
=> Script to fix Stripe webhooks

backend/routes/shops.js, backend/test/listing.test.js, backend/test/shop.util.test.js, backend/utils/shop.js
We already had a few instances in prod where the backend payment processing failed because it could not load the shop's config.json (see this [code](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/handleLog.js#L256)).
This was because the merchant had updated their shop's hostname and the dataUrl was still using the old hostname. 
This change updates the public and data URL every time a shop's config is saved.
=> Update public and data URL when hostname gets updated

backend/scripts/one-off/cryptoDirect.js
Script to backfill all shop's config.json in the staging area.
Note: initially we had discussed setting walletAddress in the shop's config in the DB but then decided not to do so. I have left the code there in case we change our mind later but I'm not planning on running it.
The plan will be to run this script directly from one of the prod container running the back-end so that it has access to the disk containing the staging area files.
=> Backfill script for direct payment launch

backend/models/external_payment.js
The order_id was removed from external_payments a while back but the model still had a reference to it.
This was causing some errors in prod when the external_payments table was getting queried. For ex:
```
2020-09-02T18:26:14.807824507Z [ERROR] dshop.routes.stripe: ⚠️ Failed to send email { SequelizeDatabaseError: column "order_id" does not exist
2020-09-02T18:26:14.808090242Z       'SELECT "id", "created_at", "updated_at", "payment_at", "external_id", "data", "amount", "fee", "net", "currency", "authenticated", "payment_intent" AS "paymentIntent", "payment_code" AS "paymentCode", "type", "created_at" AS "createdAt", "updated_at" AS "updatedAt", "order_id" AS "orderId" FROM "external_payments" AS "ExternalPayment" WHERE "ExternalPayment"."authenticated" = true AND …
```
=> Remove deprecated relationship between external_payments and orders table

backend/logic/order/order.js, backend/routes/orders.js, backend/scripts/one-off/offchainOrdersMigration.js, backend/utils/emails/newOrder.js, backend/utils/printful.js, shop/src/utils/useOrigin.js
Fix for bug #544 
If the order is off-chain (e.g. order.offerId is undefined), the order page presented to the buyer should load its data directly from the encrypted IPFS blob.
Note: also includes an unrelated small fix to the offchainOrdersMigration.js script.
=> Fix order email link

backend/logic/order/index.js, backend/utils/handleLog.js
A new paymentType argument was added to the processNewOrder logic method but in case of an on-chain transaction (e.g. marketplace transaction), it was not passed. Causing the paymentType column to remain blank for those orders in the DB.
=> Fix paymentType bug for on-chain transactions

shop/src/utils/useProducts.js
Removing this since it causes #628 
Alternatively, we can use `useProducts({ collection: 'home' })` to achieve the same thing without causing the above bug. Once we are done with themes' editor, we could define featured collections/products as a field.
=> Remove homeCollection filter

backend/logic/deploy/cdn/gcp.js, backend/utils/google.js
Adds cache invalidations during deployments if a urlMaps is not newly created.
Especially check out the invalidation paths and let me know if I'm missing anything crucial.
Ref: #669
=> Adds urlMaps cache invalidation

shop/src/components/ConfirmationModal.js, shop/src/pages/admin/settings/deployments/_DeployButton.js
Adds a little expectation management for short term improvement of #683.
Let me know if you have any feedback for verbiage or formatting.
=> Adds some deployment text to confirmation modal

backend/logic/shop/config.js
We have some instances of shops in production that have inconsistent configs in the DB where for example a webhook is not registered but the shop does seem to be configured for Printful.
This PR explicitly resets all the config fields related to Stripe/PayPal/Printful whenever one of those app is disconnected by the admin. This should hopefully help with inconsistency issues moving forward. I'll write a script in a separate PR to fix the existing data inconsistencies.
=> Reset all config fields when Stripe/Paypal/Printful is disconnected

backend/db/migrations/20201020191102-add-shop-domain-ip.js, backend/db/migrations/20201028181012-add-cdn-option.js, backend/logic/deploy/index.js, backend/models/shop.js, backend/utils/dns/clouddns.js
Adds per-shop CDN opt-in, currently to be enabled via direct DB access.
I'm not sure where the UI would this should lay so I'm leaving that for later.  Perhaps in super-admin?  I imagine this decision should be by whoever is providing the infra.
This replaces #709
=> Optional CDN deployments per shop

backend/logic/deploy/cdn/gcp.js
`Number(strSuffix)` returns a `NaN` in some cases making the certificate name `ds-deploy-mainnet-xxx-NaN` which fails the regex test on Google's side (because it contains uppercase character)
[Related logs](https://console.cloud.google.com/logs/query;pinnedLogId=2020-10-29T10:32:14.445049333Z%2Fbdnup4uigqupfwd5a;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22origin-214503%22%0Aresource.labels.location%3D%22us-west1-a%22%0Aresource.labels.cluster_name%3D%22origin%22%0Aresource.labels.namespace_name%3D%22experimental%22%0Alabels.k8s-pod%2Fapp%3D%22experimental-dshop-backend-mainnet%22;timeRange=PT1H?project=origin-214503)
=> Fix NaN bug in CDN deployment

backend/logic/printful/webhook.js, backend/logic/shop/config.js, backend/utils/paypal.js, backend/utils/stripe.js, shop/src/pages/admin/settings/payments/_DisconnectModal.js
I introduced a bug where Printful would get disconnected upon a config update :(
This should hopefully fix the issue and clean up our disconnect logic which was a bit confusing for a newbie like myself.
The main change is for the front-end disconnect modal to explicitly specify if an app should be disconnected as opposed to relying on the back-end figuring it out if the config change is related to connecting or disconnecting an app.
=> Cleanup disconnect logic

backend/logic/payments/stripe.js, backend/logic/printful/webhook.js, backend/logic/shop/health.js, backend/routes/stripe.js, backend/scripts/configCli.js, backend/utils/stripe.js
Updated the diagnose logic and configCli to use the method webhookValidation() which performs a check on the validity of the webhook's metadata (makes sure it matches the shop's authToken).
Also small misc cleanups.
=> Improve diagnose tool to detect Stripe webhook with invalid metadata

backend/app.js, backend/db/migrations/20201030222628-add-domain-index.js, backend/scripts/aws/marketplace/startup_script.sh, backend/scripts/gcp/marketplace/startup_script.sh, backend/utils/const.js, backend/utils/hostCache.js
This PR allows us to serve assembled shops from the backend by pointing a known domain at the backend.
This will require some modifications to the nginx ingress to set the `X-Forwarded-Host` header for prod deployments.
Will follow this up later with an update to DNS instructions stuff but want to get in some testing before that happens.
=> Serve dapp from backend if given a deployed hostname

backend/routes/domains.js, backend/utils/const.js, backend/utils/ip.js
Changes DNS instructions so that instead of pointing to the IPFS gateway assuming it has AutoSSL configured, to use:
- If CNAME: the hostname from `networkConfig.backendUrl`
- if A: `EXTERNAL_IP` if configured, or the external IP as seen by an ipify request, or 127.0.0.1 if localhost
Depends on: https://github.com/OriginProtocol/origin/pull/4510
=> DNS instructions to use backend address

backend/logic/deploy/dns.js, backend/logic/deploy/index.js
This will by default, CNAME shops on the default domain (e.g. `myshoop.ogn.app`) to the hostname from `backendUrl`.
=> CNAME backend host for defualt domains

shop/src/data/state.js, shop/src/pages/Product.js, shop/src/pages/cart/CartItem.js, shop/src/themes/art/components/Product.js, shop/src/themes/cake/components/Product.js, shop/src/themes/poly/components/Product.js, shop/src/themes/shared/Cart.js, shop/src/themes/shared/ProductOptions.js, shop/src/themes/shared/hoc/usePalette.js, shop/src/themes/ybm/components/Product.js
- Add variant selectbox to all themes (Closes #764)
- Allow changing quantity in cart items for all themes
- Disallow selecting more than available quantity  (Closes #774)
- Fix a glitch when no palette has been selected
- Make "Add to cart" button's state dependent on variant instead of product (so that multiple variants of same product can be added to cart)
- Use Gallery component for Cake and Art themes
=> Theme Enhancements

shop/src/pages/checkout/ChoosePayment.js
Add functionality to select the first payment option whenever the payment component mounts and the end-user has not made a selection on their own. Ensuring that once an end-user has picked an option that is the option that is selected should the end-user exit the _Payment_ page, and then return.
Resolves: https://github.com/OriginProtocol/dshop/issues/502
=> feat: Auto-select first payment option in checkout

backend/scripts/printful/downloadProductData.js
Printful seems to have [rate-limit](https://www.printful.com/docs) of 120 reqs/minute. This is causing failures during sync in some of the stores. This adds a sleep of 60s after every 75th request while getting data from printful API.
=> Wait out rate limit

backend/db/migrations/20201201125225-addPrintfulSyncing.js, backend/logic/printful/sync/downloadPrintfulMockups.js, backend/logic/printful/sync/downloadProductData.js, backend/logic/printful/sync/resizePrintfulMockups.js, backend/logic/printful/sync/writeProductData.js, backend/models/shop.js, backend/queues/fallbackQueue.js, backend/queues/printfulSyncProcessor.js, backend/routes/auth.js, backend/routes/shops.js, shop/src/data/state.js, shop/src/pages/admin/settings/apps/PrintfulSync.js
Related to #796 
Pushes printful manual sync requests to the queue and keeps track of the status through a DB column. The status is long-polled with a 5s duration on the frontend.
=> Make printful syncing async

shop/src/utils/useToken.js
Fixes #818.
It happened only when switching from other tokens to ETH. Since the `setState` uses a reducer, the `contract` key was never really overwritten even when selecting ETH.
=> Clear token state when changing selection in `useToken` hook

backend/logic/printful/index.js, backend/test/printful.test.js, backend/test/utils.js
Currently in case of a Printful auto-fulfillment error, the merchant receives an email.
But in the admin UI, the orders page and order details page do not show any obvious warning that something went wrong and needs the merchant's attention.
This change stores any auto-fulfillment error in the order's metadata in the DB. That will cause the UI to display a red flag next to the order on the orders page and an error message on the order details page.
Note: as a future improvement, we could discard this error if the merchant submits the order manually via the order details page.
=> Surface Printful auto-fulfillment failures in the admin UI

backend/queues/index.js, backend/queues/queues.js
Fix #872 
- Disable discord notifications on autossl failures. Some failures are expected and the noise/signal ratio was bad.
- Disable all discord notification for gitcoin - that shop is no longer alive.
- Enable sentry logging on business critical queues
=> Skip discord notifications for autossl failures

backend/routes/orders.js, backend/utils/emails/newOrder.js, packages/services/start.js, packages/utils/generatePrintfulOrder.js
The back-end was failing to send email due to this error firing:
https://github.com/OriginProtocol/dshop/blob/06275facb6bf17f50c5d11f8aa7aa9ca5808d868/backend/logic/printful/webhook.js#L183
This was caused by auto-fulfilled orders not having a correct external id set.
It is a bit confusing but both the dshop admin FE and the back-end can call the method generatePrintfulOrder.
In the case it was called by the backend, the field order.orderId did not exist.
Fixed by using order.shortId in both case and making sure shortId is present on orders returned to the front-end.
This should fix #874
Also improved the logging in the sendNewOrderEmail method to include the shopId in order to make future email failure related investigation for a given shop easier.
=> Fix shipping email failures

backend/queues/queues.js, backend/queues/txProcessor.js, backend/routes/_makeOffer.js, shop/src/pages/admin/_Nav.js, shop/src/pages/admin/onboarding/_Banner.js, yarn.lock
Fix for #912 
The tx queue was not configured to be retry-able. If a tx hash failed lookup because it was too fresh to show up on Alchemy, the order would fail.
Added retries to the tx queue and also cleaned up the makeOffer queue so that retries are configure at init time rather than having to do it when posting every job.
Bull's reference doc: <https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md>
=> Add retries to the tx queue

backend/app.js
Don't want a second set of queue processors running on separate state storage when I bring up the second mainnet environment.  This adds a way to disable them.
=> Adds the ability to disable queue processing

shop/src/pages/admin/products/Edit.js
Fixes #930
When a new product was saved the selected collections would clear. This was caused by listening on changes to `collections.length`. After the product was pushed to the DB and fetched, the useEffect() would not update bc even though collections had changed `collections.length` did not change.
=> fix new product selected collections

shop/src/pages/super-admin/setup/_SetupLayout.js
Despite being unsure about how this change may affect the prod instance of Dshop, I'm requesting for it to be reviewed in the context of #476. In other words, although the issue was only reported with respect to the 'setup' page seen by "super-admins"/devs, the commit I'm submitting has applied the new color to the following pages as well:
localhost:3000/#/admin/login
localhost:3000/#/admin/signup
localhost:3000/#/admin/forgot-password
Sample:
=> Addressing usability issue - #476

backend/routes/shops.js
Looks like a not-insignificant chunk of shops are running into a domain conflict causing deploy failures after the recent addition of a validation check.  This uses `shop.hostname` instead of `dataDir` (auth_token) for deployment subdomain in the deploy route to help normalize things a bit more.  
This might not be the only cause of the conflict.  We were playing kinda fast and loose with DNS names.  Will continue to monitor and work on fixing.
=> Incorrect hostname used in deployments

shop/src/themes/shared/checkout/Information.js, shop/src/themes/shared/checkout/Shipping.js, shop/src/themes/shared/checkout/_Summary.js, shop/src/themes/shared/checkout/_Taxes.js
On the `master` branch, only users of the **Default** theme can charge taxes on orders. 
I am committing code that's intended to support this feature for other themes. 
_UI testing_ performed in my dev environment:
https://user-images.githubusercontent.com/10854442/142399872-3d0c2f80-95f9-43bb-8c77-e2c0a6401440.mov
Jump to:
0:53 - Test that taxes are loaded for a customer from a taxed 'province' [Desktop]
2:09 - Test that taxes are loaded for a customer from a taxed 'country' [Desktop]
3:20 - Test that taxes are loaded for a customer from a taxed 'country' [Mobile]
4:06 - Test that taxes are loaded for a customer from a taxed 'province' [Mobile]
**Important**
In the video, the **value** of tax calculated is incorrect; this has been addressed with help from @franckc (see …
=> Display taxes in order summary on shops using themes

shop/src/components/ConfirmationModal.js, shop/src/utils/useConfig.js, shop/src/utils/useDashboardStats.js, shop/src/utils/useIsMounted.js, shop/src/utils/usePGP.js, shop/src/utils/useShopConfig.js
This resolves react warnings about setting component state after the component has unmounted. 
Most of the memory leaks happened inside of hooks that had async operations. Once the async operation completed it failed to check wether the component was still mounted. It introduces a new hook `useIsMounted` that makes it reusable to check wether a component is mounted/unmounted.
=> Component Memory Leaks
