backend/scripts/backfill.js, backend/utils/handleLog.js
- Minor fixes
- Updated comments
- Added option in the logic for processing events to skip sending notifications (email, discord).
=> Minor updates to the backfill script

backend/routes/shops.js, backend/utils/deployShop.js, backend/utils/products.js, shop/src/pages/super-admin/setup/SignUp.js
execFile escapes arguments, preventing command injection.
=> Convert exec's to execFile

backend/utils/products.js, shop/src/pages/Product.js, shop/src/pages/admin/order/_PaymentInfo.js, shop/src/pages/admin/products/Edit.js
=> Product variant fixes

backend/utils/primeIpfs.js
=> Handle errors in bottleneck when doing prime calls

backend/package.json, backend/routes/printful.js, backend/routes/shops.js, backend/utils/emailer.js, backend/utils/handleLog.js, backend/utils/printful.js, backend/utils/templates/printfulOrderFailed.js, backend/utils/templates/pritnfulOrderFailedTxt.js, package.json, packages/utils/.eslintrc.js, packages/utils/Countries.js, packages/utils/README.md, packages/utils/generatePrintfulOrder.js, packages/utils/package.json, shop/package.json, shop/src/components/CountrySelect.js, shop/src/components/ShippingForm.js, shop/src/data/state.js, shop/src/pages/admin/collections/Show.js, shop/src/pages/admin/order/Printful.js, shop/src/pages/admin/products/Edit.js, shop/src/pages/checkout/ChoosePayment.js, shop/src/pages/checkout/Information.js, shop/src/pages/checkout/Shipping.js, shop/src/utils/useCollections.js, shop/src/utils/useProducts.js
Add a way to edit collection title and fix #42
=> Add a way to edit collection title and fix #42

backend/app.js, backend/queues/fallbackQueue.js, backend/routes/health.js
Adds health check endpoints that I'm planning on using for kubernetes probes.
=> Health check endpoints

backend/scripts/validatePayments.js
- Added option to check payment for all shops
- Added mode for checking the Stripe config for shops
=> Update to validatePayment script

backend/db/migrations/20200715221932-addIpfsGatewayToShopDeployments.js, backend/models/shop_deployment.js, backend/routes/shops.js, backend/utils/deployShop.js
Fix for https://github.com/OriginProtocol/dshop/issues/221
=> Backend: store IPFS gateway associated with the pinner in the shop_deployments table

backend/app.js
Better to have generic errors in order to not risk revealing any details about our infra...
=> Backend server default error handler: return generic error messages in prod

backend/routes/domains.js, shop/src/pages/admin/settings/appearance/Edit.js
=> Small copy repairs

backend/queues/makeOfferProcessor.js
- Default to using Network PK
- Capture exceptions in Sentry
=> [offer processor] Default to using the network PK if the shop's config does not have a PK

backend/scripts/reprocessEvent.js
We have a handful of events that the listener failed processing in prod.
I'm planning on using this script to manually re-process them.
=> Script for reprocessing events

backend/routes/shops.js, backend/utils/deployShop.js, backend/utils/products.js, shop/public/template.html, shop/src/components/SentryErrorBoundary.js, shop/src/data/state.js, shop/src/index.js, shop/src/pages/admin/Dashboard.js, shop/src/pages/admin/settings/Advanced.js, shop/src/pages/admin/settings/payments/StripeModal.js, shop/src/utils/useDashboardStats.js, shop/webpack.config.js
- Logs all errors in admin pages by default
- Allows the shop admin to enable/disable logging errors for users
=> Sentry changes

backend/routes/auth.js
Don't give any potential attackers useful information.
Fixes #290
=> Don't leak auth failure reasons

backend/routes/stripe.js
Adds a bit of error handling and instrumentation around stripe webhook body parsing to diagnose #307 and #310
=> Stripe webhook robusto

backend/routes/auth.js, backend/routes/networks.js, shop/src/pages/App.js, shop/src/pages/super-admin/networks/_Form.js
Add Google Analytics to deployer admin pages
=> Google Analytics

backend/routes/shops.js
=> Prefix web3 private key when set

backend/routes/stripe.js
This change should allow us to coexist with other eCommerce software by failing gracefully if we find a Stripe payment event that wasn't created by Dshop.
This should be compatible with any shops deployed in the last 3 months.  If anything thinks we need to support older versions, speak up.
Fixes #298
=> Stripe webhook graceful failures

backend/scripts/stripe.js
Was using this this week to verify Webhook configurations without actually having access to the users' dashboard.  Figure it might be useful to others.
=> Stripe RESTful API CLI script

backend/routes/shops.js
=> log deployment duration

backend/utils/handleLog.js
For troubleshooting it is helpful to have all the events in the DB, not only the ones we think are related to dshop.
=> [Listener] Store all marketplace events

backend/routes/stripe.js, backend/utils/stripe.js, packages/utils/stripe.js, shop/src/pages/admin/settings/payments/StripeModal.js
=> Stripe keys validation and error handling

backend/queues/queues.js, backend/scripts/gcp/marketplace/startup_script.sh
Modify the image install script to setup redis and configure REDIS_URL so that the deployer uses it.
=> Install and configure Redis for the deployer's GCP image

backend/queues/fallbackQueue.js, backend/routes/paypal.js, backend/routes/shops.js, backend/routes/stripe.js, backend/utils/paypal.js, backend/utils/stripe.js, packages/utils/stripe.js, shop/src/pages/admin/settings/payments/List.js, shop/src/pages/admin/settings/payments/StripeModal.js, shop/src/pages/admin/settings/payments/_DisconnectModal.js
=> Stripe webhook changes

backend/routes/exchange-rates.js, packages/utils/formatPrice.js, shop/public/images/caret-dark.svg, shop/src/components/CurrencySelect.js, shop/src/components/ProductList.js, shop/src/data/state.js, shop/src/pages/Product.js, shop/src/pages/_Footer.js, shop/src/pages/cart/Cart.js, shop/src/pages/cart/CartItem.js, shop/src/pages/checkout/CheckoutItem.js, shop/src/pages/checkout/ChoosePayment.js, shop/src/pages/checkout/Shipping.js, shop/src/pages/checkout/Summary.js, shop/src/pages/checkout/payment-methods/PayPal.js, shop/src/pages/checkout/payment-methods/Stripe.js, shop/src/utils/useCurrencyOpts.js, shop/src/utils/usePrice.js
=> Currency override for browsing/checkout

devops/cloudbuild.ui.yaml, devops/syncBucket.js, devops/updateBuilds.js, package.json, yarn.lock
- Example builds.json: https://storage.cloud.google.com/dshop-ui-staging/builds.json
- Bucket contents: https://console.cloud.google.com/storage/browser/dshop-ui-staging;tab=objects?forceOnBucketsSortingFiltering=false&project=origin-214503&prefix=
- Deployed IPNS contents: https://ui.ogn.app/
- Deployed IPFS contenst: https://ipfs.io/ipfs/QmZ3v5JUmWZByXU8kmJsBDvVELgs2USQJdxkDvmmLHjrm5
(builds.json and bucket contents don't currently match because of my weird testing but they will)
With this proposed solution, an `index.html` build would load builds.json, use the latest hash to load the latest assets.  I haven't built and tested that yet.
Ref #180
=> Adds pipeline to build and deploy generic UI

backend/config.js, backend/utils/_ipfs.js
Misc cleanup of config related code:
- Deleted method getSiteConfig since it was not used anywhere
- Refactored method resolveIPFSGateway
=> Config code cleanup

backend/routes/auth.js
=> Use EC2 instance ID for the initial super user password

backend/routes/_auth.js, shop/src/pages/App.js, shop/src/pages/Password.js, shop/src/pages/admin/discounts/Edit.js, shop/src/pages/admin/order/Printful.js, shop/src/pages/admin/settings/Console.js, shop/src/pages/admin/settings/Server.js, shop/src/pages/affiliates/JoinModal.js, shop/src/pages/checkout/Discount.js, shop/src/pages/checkout/payment-methods/Stripe.js, shop/src/pages/checkout/payment-methods/uphold/_Logout.js, shop/src/pages/super-admin/shops/shop/_ActivateBuild.js, shop/src/utils/useAffiliateEarnings.js, shop/src/utils/useBackendApi.js, shop/src/utils/useDiscounts.js, shop/src/utils/useOrder.js, shop/src/utils/useOrders.js, shop/src/utils/usePrintful.js, shop/src/utils/useRest.js, shop/src/utils/useShippingZones.js, shop/src/utils/useShopConfig.js
Part of #303, encodes `authToken` in request headers in client side and decodes it on the server side middleware.
=> Encode authToken before sending it from client

backend/routes/stripe.js
Looks like Stripe sends the pending webhook events, even if the webhook has been deregistered. 
This PR checks if the event (which fails the sign check) is already processed and ignores them instead of returning 400 (which makes Stripe to resend it again).
=> Ignore duplicate webhook events

backend/package.json, backend/routes/networks.js, backend/routes/shops.js, backend/utils/deployShop.js, backend/utils/dns/clouddns.js, backend/utils/dns/cloudflare.js, backend/utils/dns/route53.js, backend/utils/string.js, shop/src/pages/super-admin/networks/_Form.js, yarn.lock
This adds AWS Route53 support for shop DNS configuration to the backend.  Will followup with the UI update for GCP credentials.
=> Adds Route 53 support to backend

shop/src/pages/admin/onboarding/Onboarding.js, shop/src/pages/admin/settings/shipping/Edit.js, shop/src/pages/admin/settings/shipping/_PrintfulShippingAlert.js
=> Update printful shipping UI

shop/src/pages/admin/_Menu.js, shop/src/pages/admin/order/Order.js
The roles are stored in different cases in DB. We should normalize them with a script sooner or later.
=> Case insensitive role checks

backend/routes/printful.js, backend/utils/discounts.js, backend/utils/printful.js, shop/src/data/state.js, shop/src/pages/admin/order/_PaymentInfo.js, shop/src/pages/admin/settings/apps/PrintfulSync.js, shop/src/pages/checkout/Information.js, shop/src/pages/checkout/Summary.js, shop/src/themes/cake/components/checkout/_Summary.js, shop/src/themes/shared/checkout/_Summary.js, shop/src/utils/useShippingZones.js
=> Printful related changes

backend/routes/shops.js, shop/src/pages/admin/settings/Settings.js, shop/src/pages/admin/settings/checkout/Edit.js, shop/src/pages/admin/settings/checkout/_CountryTaxEntry.js, shop/src/pages/admin/settings/checkout/_Taxes.js, shop/src/pages/admin/settings/checkout/_taxInputValidation.js, shop/src/pages/checkout/Information.js, shop/src/utils/formHelpers.js
=> Manual Taxes

shop/src/pages/admin/settings/apps/PrintfulModal.js
=> Printful: auto-fulfill by default

backend/scripts/createListing.js, shop/README.md
=> Fixes createListing.js script and adds mention of it in README

shop/src/utils/useProducts.js
Part of #620 that I missed in my previous PR
=> Fix collection edit page

backend/scripts/printful/getProducts.js, backend/scripts/printful/writeProductData.js, backend/utils/products.js, shop/src/pages/admin/products/Edit.js
=> Printful pagination and description override

backend/logic/deploy/bucket/gcp.js
=> Add retries to GCS bucket uploads

backend/logic/printful/webhook.js, backend/routes/auth.js, backend/routes/collections.js, backend/routes/printful.js
=> Replace encConfig.get with decryptConfig

backend/db/migrations/20200226172508-createTables.js, backend/db/migrations/20201103132608-updateDiscountTypeEnum.js, backend/db/migrations/20201103132751-addDiscountDataCol.js, backend/db/migrations/20201105121828-addDiscountCols.js, backend/enums.js, backend/logic/discount/index.js, backend/models/discount.js, backend/routes/discounts.js, backend/test/discount.test.js, backend/test/utils.js, backend/utils/discounts.js, shop/src/components/payment/crypto/Crypto.js, shop/src/components/payment/crypto/CryptoDirect.js, shop/src/data/state.js, shop/src/pages/Product.js, shop/src/pages/admin/Admin.js, shop/src/pages/admin/discounts/Edit.js, shop/src/pages/admin/discounts/List.js, shop/src/pages/admin/discounts/PaymentSpecific.js, shop/src/pages/admin/discounts/_Tabs.js, shop/src/pages/checkout/Discount.js, shop/src/pages/checkout/Summary.js, shop/src/themes/art/components/Product.js, shop/src/themes/cake/components/Product.js, shop/src/themes/poly/components/Product.js, shop/src/themes/shared/checkout/_Summary.js, shop/src/themes/ybm/components/Product.js, shop/src/utils/useDiscount.js, shop/src/utils/usePaymentDiscount.js
=> Payment-specific discounts

backend/logic/discount/index.js, backend/queues/txProcessor.js, backend/test/discount.test.js
Fix non-payment-specific discounts that seems to be broken because of my previous PR #746
=> Fix other discounts

backend/logic/products/index.js, backend/scripts/printful/writeProductData.js, shop/src/components/ImagePicker.js, shop/src/pages/admin/products/Edit.js, shop/src/pages/admin/products/_EditVariants.js
Allows user to change images on their Printful store products. Doesn't sync images for the existing variants if they have been updated manually by the seller
=> Allow printful images to be changed

shop/src/pages/About.js
=> Remove duplicate content

backend/db/migrations/20201110195338-add-shop-indexes.js, backend/utils/hostCache.js
=> Check shop.hostname for local backend serving

backend/db/migrations/20201110120605-addExcludeShipping.js, backend/models/discount.js, backend/routes/discounts.js, backend/test/discount.test.js, backend/test/utils.js, packages/utils/calculateCartTotal.js, shop/src/pages/admin/discounts/Edit.js, shop/src/pages/checkout/Discount.js
Related Issue: https://github.com/OriginProtocol/dshop/issues/745
=> Add Option to exclude shipping from Discount

shop/src/data/state.js, shop/src/pages/Product.js, shop/src/pages/cart/CartItem.js, shop/src/themes/shared/Cart.js, shop/src/utils/getMaxQuantity.js
Fixes maxQuantity computation for shops with `config.inventory` not set or set to false.
=> Fix maxQuantity 

shop/src/components/payment/crypto/Crypto.js, shop/src/utils/useToken.js
=> Add token decimal support

.github/workflows/backend.yml, backend/test/cart.test.js, backend/test/discount.test.js, backend/test/setup.js, backend/test/utils.js
Adds GH action to run backend tests and fixes some things along the way.
=> GH Action tests for backend

backend/logic/deploy/bucket/gcp.js
=> Retry on 503s for GCS bucket uploads

shop/src/pages/admin/order/Order.js
=> Change in Contract tab rendering logic

backend/logic/deploy/cdn/aws.js, backend/logic/deploy/index.js, backend/routes/domains.js
Brings domain handling in line between the custom domain API endpoints and the deployment workflow.
Fixes #835
=> Fixes custom domain handling with CDN deployments

backend/logic/order/index.js, backend/queues/fallbackQueue.js, backend/queues/index.js, backend/utils/discordWebhook.js
Closes #807 
- Posts any job failure in queues to the Discord webhook
- Formats the way the new order messages are shown in the channel
=> Post queue errors to Discord webhook

shop/src/pages/admin/Orders.js
Added additional fields to the Orders CSV, as requested in #499
CSV import with changes highlighted in yellow:
=> Orders csv enhancement

backend/utils/shop.js
=> Encode dataDir in fetch

shop/src/components/payment/crypto/CryptoDirect.js, shop/translation/crowdin/all-messages.json
Reverts OriginProtocol/dshop#816
=> Revert "Response to #15 - UI should indicate user can't pay with ERC20 if ETH balance is 0"

shop/src/utils/generateVariants.js
I have not been able to replicate the behavior mentioned in #833 after making the change attached.
=> Resetting Variant ID when new variants are generated

backend/logic/printful/sync/writeProductData.js, backend/queues/index.js, backend/scripts/printful/getProduct.js, backend/utils/discordWebhook.js
Trying to reduce the number of printful queue failures
=> Printful bug fixes

packages/services/index.js, packages/services/package.json, yarn.lock
Due to some major upgrade to the ipfs package, our local IPFS daemon was broken.
The new IPFS interface requires to create separately a node, an HTTP API server and an HTTP  gateway.
=> Fix local IPFS service

backend/scripts/one-off/fix-printful-variant-ids.js
The script was failing on prod. After nuking my local `node_modules` and reinstalling deps, I was able to reproduce it. Guess it has to do with updated `commander` version in this PR #869. 
The other scripts might be broken too, should probably update them before we use any.
=> Fix one-off script

backend/routes/printful.js, backend/utils/emails/newOrder.js
Added some instrumentation.
Fixed a bug causing the event_type field to not get populated in the external_events DB table.
Should hopefully help with the investigation for #874 and #880
=> Improve logging for Printful events processing

shop/src/components/icons/Clipboard.js, shop/src/pages/admin/onboarding/Onboarding.js, shop/src/pages/admin/onboarding/_Banner.js, shop/src/pages/admin/settings/List.js, shop/translation/crowdin/all-messages.json
#259 
The banner on the 'Onboarding page' will display the shop URL _if_ the number of tasks left for an admin to "Finish setting up (their) store" _is less than half_ the total amount. 
Demo:
https://user-images.githubusercontent.com/10854442/107500364-15e0a680-6bbc-11eb-959c-7f02e7b352de.mov
Tested browsers:
Brave: Version 1.19.90 Chromium: 88.0.4324.146 (Official Build) (x86_64)
Safari: Version 14.0.3 (15610.4.3.1.6, 15610)
Firefox: 84.0.2 (64-bit)
=> Display shop url

shop/src/pages/admin/onboarding/Onboarding.js, shop/translation/crowdin/all-messages.json
=> Reading material for new merchants

backend/logic/deploy/index.js, backend/routes/domains.js, backend/test/shop.test.js, backend/test/utils.js, backend/utils/dns/index.js
=> Domain ownership check

backend/logic/deploy/index.js
Seeing more of these errors than I expected.  Adding context as @DanielVF requested.
=> Instrumentation for domains

backend/logic/deploy/index.js
Help narrow down the errors we're seeing a bit.
=> Changes error message for a bit of clarity

backend/routes/users.js
`/resend-email` should be sending a bool for `success`
=> Fix bad output for /resend-email

backend/app.js
=> Minor sanitization

.github/workflows/snyk.yml, .snyk, README.md, SECURITY.md
Description:
This is a snyk github action to run upon the push of a feature branch.
Note:
There are some vulnerabilities that I'd like to be reviewed by the team before before ignoring them. Currently it is set to succeed despite the gate conditions.
=> Basic Snyk github action

backend/README.md
=> Replaced a section titled 'Migrations'

shop/src/utils/useShipping.js, shop/translation/crowdin/all-messages.json
In the pull request [mentioned above](https://github.com/OriginProtocol/dshop/pull/950/files), I forgot to apply the fix to all of DShop's available themes. If merged, this PR will fix that error.
=> Extension of PR #950 

shop/buildThemes.sh, shop/src/utils/usePGP.js, shop/translation/crowdin/all-messages.json
Addresses #990 by using absolute paths while loading the OpenPGP script.
=> Updated the "usePGP" module
